version: "3"
services:
  master:
    container_name: master
    image: jenkinsci/jenkins:2.6.1
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    links:
      - slave01
      - slave02

  slave01:
    container_name: slave01
    image: jenkins/slave
    environment:
      - JENKINS_SLAVE_SSH_PUBLIC=
    
  slave02:
    container_name: slave02
    image: jenkins/slave
    environment:
      - JENKINS_SLAVE_SSH_PUBLIC=
