version: "3"
services:
  master:
    container_name: master
    image: jenkins/jenkins:2.289.3
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_master:/var/jenkins_home
    links:
      - slave01
      - slave02

  slave01:
    container_name: slave01
    image: jenkins/ssh-slave:latest
    volumes:
      - ./jenkins_slave:/var/jenkins_home
    env_file:
      - var.env

  slave02:
    container_name: slave02
    image: jenkins/ssh-slave:latest
    volumes:
      - ./jenkins_slave:/var/jenkins_home
    env_file:
      - var.env
