version: "3.8"
services:
  master:
    container_name: master
    image: jenkins/jenkins:2.289.3
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_master:/var/jenkins_home
    links:
      - slave01
      - slave02

  slave01:
    container_name: slave01
    image: jenkins/ssh-slave:alpine
    volumes:
      - ./jenkins_slave:/home/jenkins
    env_file:
      - var.env

  slave02:
    container_name: slave02
    image: jenkins/ssh-slave:alpine
    volumes:
      - ./jenkins_slave:/home/jenkins
    env_file:
      - var.env
